use derive_builder::Builder;
use serde::{Deserialize, Serialize};

use uuid::Uuid;

use crate::error::{PesaPalError, PesaPalErrorResponse, PesaPalResult};

use super::PesaPal;

pub const SUBMIT_ORDER_REQUEST_URL: &str = "api/Transactions/SubmitOrderRequest";

/// Submit Order Request
#[derive(Debug, Clone, PartialEq, Serialize)]
pub struct SubmitOrderRequest {
    /// Unique merchant reference
    pub id: String,
    /// Currency which is used to charge the customers
    pub currency: String,
    /// Amount to be processed
    pub amount: u64,
    /// Description of the order
    pub description: String,
    /// A URL which PesaPal will redirect to process the payment
    pub callback_url: String,
    /// A URL which will redirect the client incase the click on cancel request
    pub cancellation_url: Option<String>,
    /// Represents IPN URL which PesaPal uses to end notification after the
    /// Payments have been processed
    ///
    /// You are required to register all IPN Urls
    pub notification_id: String,
    /// Billing address of the customer
    pub billing_address: BillingAddress,
}

/// The billing address of a customer
#[derive(Debug, Clone, PartialEq, Serialize, Default)]
pub struct BillingAddress {
    /// customer's email address.
    ///
    /// This is Optional if phone number has been provided
    /// Otherwise mandatory
    ///
    /// The BillingAddress will fail if this is not met
    pub email_address: Option<String>,
    /// Customer's Phone Number
    ///
    /// This is optional if email address has been provided,
    /// Otherwise mandatory
    ///
    pub phone_number: Option<String>,
    /// country code in [ISO-3166-1]
    ///
    /// It is usually two characters long
    ///
    /// https://en.wikipedia.org/wiki/ISO_3166-1
    pub country_code: Option<String>,
    /// Customer's first name
    pub first_name: Option<String>,
    /// Customer's middle name
    pub middle_name: Option<String>,
    /// Customer's last name
    pub last_name: Option<String>,
    // Main Address
    pub line_1: Option<String>,
    // Alternative Address
    pub line_2: Option<String>,
    /// Customer's City
    pub city: Option<String>,
    /// Customer's state
    ///
    /// Maximum: three character long
    pub state: Option<String>,
    // Customer's postal code
    pub postal_code: Option<String>,
    /// Customer's zip code
    pub zip_code: Option<String>,
}

impl From<SubmitOrder<'_>> for SubmitOrderRequest {
    fn from(value: SubmitOrder) -> Self {
        Self {
            id: Uuid::new_v4().to_string(),
            currency: value.currency,
            amount: value.amount,
            description: value.description,
            callback_url: value.callback_url,
            notification_id: value.notification_id,
            cancellation_url: value.cancellation_url,
            billing_address: value.billing_address,
        }
    }
}

/// The Submit Order response after a payment has been created successfully
#[derive(Default, Debug, Clone, PartialEq, Eq, Deserialize)]
pub struct SubmitOrderResponse {
    /// Unique order id generated by PesaPal
    pub order_tracking_id: String,
    /// Unique ID received as part of the [SubmitOrderRequest]
    pub merchant_reference: String,
    /// URL generated that contains the payment instructions.
    ///
    /// Redirect to this URl or load it within an iframe
    pub redirect_url: String,
    /// Error message
    pub error: Option<PesaPalErrorResponse>,
    /// Response Message
    pub status: String,
}

/// This is the submit order builder
#[derive(Builder, Debug, Clone)]
#[builder(build_fn(validate = "Self::validate"))]
pub struct SubmitOrder<'pesa> {
    #[builder(pattern = "owned")]
    pub client: &'pesa PesaPal,
    #[builder(setter(into))]
    #[doc = r"Currency which is used to charge the customers"]
    pub currency: String,
    #[doc = r"Amount to be processed"]
    pub amount: u64,
    #[builder(setter(into))]
    #[doc = r"Description of the order"]
    pub description: String,
    #[builder(setter(into))]
    pub callback_url: String,
    #[builder(setter(into, strip_option), default)]
    pub cancellation_url: Option<String>,
    #[builder(setter(into))]
    pub notification_id: String,
    pub billing_address: BillingAddress,
}

impl SubmitOrderBuilder<'_> {
    /// Validate that either the email address or the phone number is provided
    fn validate(&self) -> Result<(), String> {
        if let Some(billing_address) = &self.billing_address {
            if billing_address.email_address.is_none() && billing_address.phone_number.is_none() {
                return Err("either email or phone number must be provided.".to_string());
            }
        }

        Ok(())
    }
}

impl<'pesa> SubmitOrder<'pesa> {
    pub fn builder(client: &'pesa PesaPal) -> SubmitOrderBuilder<'pesa> {
        SubmitOrderBuilder::default().client(client)
    }
}

impl SubmitOrder<'_> {
    pub async fn send(self) -> PesaPalResult<SubmitOrderResponse> {
        let url = format!("{}/{SUBMIT_ORDER_REQUEST_URL}", self.client.env.base_url());
        println!(
            "params : {:?}",
            serde_json::json!(Into::<SubmitOrderRequest>::into(self.clone()))
        );

        let response = self
            .client
            .http_client
            .post(url)
            .bearer_auth(&self.client.authenticate().await?.token)
            .json::<SubmitOrderRequest>(&self.into())
            .send()
            .await?;

        let response_json: serde_json::Value = response.json().await?;

        if let Some(err) = response_json.get("error") {
            let err: PesaPalErrorResponse = serde_json::from_value(err.clone())?;
            return Err(PesaPalError::SubmitOrderError(err));
        }

        let res = serde_json::from_value(response_json)?;

        Ok(res)
    }
}
